before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - test
   - coverage

test:
  tags:
     - ece651
  stage: test
  script: gradle build
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public
